### PR TITLE
Github OAuth

### LINKED ISSUE #41: Google OAuth

### PR DESCRIPTION
**Pull request by chloeelim**
(Ignore the linter errors, they're not pushed to this PR)
(Also, you might have to delete your docker container + image? to run the migrations if you're using Docker, not sure if there's a better way around it)

Implementation TLDR:
* Used Github OAuth + Github API
* Will first redirect to Github to ask user to allow our app to access their data (When clicking the first button in the login page)
* Upon user authorisation on Github, Github will redirect the user back to the frontend ('OAuth Page') with a code param
* Frontend will then send this code param back to the backend (new auth API endpoint for authorizing oAuth logins)
* Backend then uses this code to query GitHub for the user's access token. This access token allows our app to make authenticated requests to the Github API to retrieve user data.
* So, now with the user access token, our backend will retrieve user data. To 'store' oAuth users in our DB I used the user's github ID (which I assume is unique, other user properties might change and I assume the ID won't)- this is stored in a new githubId column in the users table.
  * The backend tries to find a user with this githubId, if it succeeds, it means the user already exists. Since they've already been authenticated, we can safely log the user in.
  * Else, if the githubId doesn't exist, that means that's a new user. Frontend will have to prompt user for more details (username + email), and resend them back to another backend endpoint to actually create the user and then log the user in.

https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g17/assets/79991214/39579952-2c16-4cc9-b509-e4f6ecf13754

### CODE REVIEW

**Comment by sltsheryl** [comment]
https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g17/assets/96589109/9bfee414-5abf-4f32-b317-1a569681c0dd

did i set it up correctly, i tried logging in but it says page not found

**Review by seelengxd — COMMENTED** [review]
environment variables = ?

**Comment by sltsheryl** [comment]
> environment variables = ?

i saw the update thx

**Comment by chloeelim** [comment]
woopss sorry just updated them properly @seelengxd @sltsheryl

**Comment by chloeelim** [comment]
oh shoot missed out another env var in frontend please update if needed : " )

**Review by seelengxd — APPROVED** [review]
lgtm

**Pull request merged**
