### PR TITLE
Matching queue

### PR DESCRIPTION
**Pull request by sltsheryl**
(update .env matching, collaboration)
- set up the producer on the matching side in `matchingHandler.ts`
- currently, i am able to receive messages on rabbitmq
- to run:
`brew install rabbitmq`
`rabbitmq-plugins enable rabbitmq_management`
`brew services start rabbitmq`
go to `http://localhost:15672/`
login with username `guest`, password `guest`

### CODE REVIEW

**Comment by seelengxd** [comment]
i have not gotten the consumer to consume a message but initially, even
`console.log(`[*] Waiting for messages in ${queue}. To exit press CTRL+C`);` would not print

the reason is collaboration-service currently **does not** run app.ts at all (so the rabbitmq function call also was not run)
might need to change the npm start to run both app.ts and that websocket thing

"start": "HOST=localhost PORT=8081 npx y-websocket & nodemon --exec ts-node ./app.ts",

(but this also requires killing the first process each time so might need a cleaner way to do this)

**Comment by seelengxd** [comment]
image

i changed like nothing but it suddenly works :D

**Comment by sltsheryl** [comment]
same thanks! thanks for providing the hacky fix to run both things simultaneously, though yes we shd find a better way soon!

**Comment by sltsheryl** [comment]
Currently there are two kinds of matching - practice room with your friend (so you'll define the room id which chloe implemented AND the randomised matching with suitable partner). 

In the end, i decided not to add the practice room in the db of pairs, but only the matching

https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g17/assets/96589109/7e5b7ad7-0183-444f-a613-4166dac4c003

**Comment by sltsheryl** [comment]
In the video, you'll see the queue in rabbit mq has zero messages, that's cuz its only shown if something is still present in the queue. 

Here, it's immediately consumed by the collaboration service (if u comment that part in the collaboration service, we can see the sent message in the queue - addressing the part in the assignment "Show the state of the application/state of the queue to indicate a match was found."

**Comment by sltsheryl** [comment]
# Not implemented yet (prob in another PR)
Fetching of questions in the collaboration service
currently question_ids start off as an empty array

**Review by seelengxd — APPROVED** [review]
LGTM!

**Pull request merged**
