### PR TITLE
fix(api-gateway): fix nginx file

### PR DESCRIPTION
**Pull request by seelengxd**
after fixing this + a permission issue

https://master.da377qx9p9syb.amplifyapp.com/
(frontend/question/user services work!)

related to #88

### CODE REVIEW

**Review by sltsheryl — APPROVED** [review]
nice gzgz

**Comment by sltsheryl** [comment]
im not sure if its supposed to be like that but i was using the link then after logging in the qn bank doesnt show up so i reloaded and it redirects back to login page so hmm...

**Comment by seelengxd** [comment]
oh no replicated on chrome
it just magically worked on firefox

**Comment by sltsheryl** [comment]
> oh no replicated on chrome it just magically worked on firefox

hmm btw firefox the matching also didn't work

**Comment by seelengxd** [comment]
yep only user/question services have been deployed so far >_<

**Pull request merged**
