### PR TITLE
fix: spacing styling

### PR DESCRIPTION
**Pull request by sltsheryl**
very trivial spacing stuff

Screenshot 2023-11-11 at 2 35 09 AM

### CODE REVIEW

**Review by seelengxd — APPROVED** [review]

**Comment by sltsheryl** [comment]
@seelengxd weird phenomenon: ystd the deployed forum was working fine, now its not

**Comment by sltsheryl** [comment]
Screenshot 2023-11-11 at 10 14 10 AM

**Comment by seelengxd** [comment]
somehow the forum db disappeared - idk how but rerunning `npx prisma db push` fixed it

**Comment by sltsheryl** [comment]
> somehow the forum db disappeared - idk how but rerunning `npx prisma db push` fixed it

hmmm 🧐 thanks

**Pull request merged**
