### PR TITLE
Forum service

### LINKED ISSUE #85: forum
- forum to ask questions

### PR DESCRIPTION
**Pull request by carriezhengjr**
Fixes #85 

Main forum page:
- [x] View all posts (title, author, date & time of creation, no. of upvotes) with styling
  - [x] Show total no. of comments for each post on main Forum page
- [x] Add a post 
  - [x] Disable submit if title is not filled or with whitespaces; description is not filled or with whitespaces or with line breaks.
- [x] Search for posts
- [x] Sort posts by: Newest to Oldest (default), Most Votes
- [x] Pagination

Individual post page:
- [x] View post (title, author, date & time of creation, no. of upvotes, description with formatting) with styling
- [x] Delete post (button only visible to author)
- [x] Upvote post
- [x] Edit post
- [x] Downvote post (it's an un-upvote function, so users won't be discouraged to post)

Comments (on individual post page):
- [x] View all comments (author, date & time of creation, no. of upvotes)
- [x] Add a comment
- [x] Delete a comment (button only visible to author)
- [x] Upvote comments
- [x] Downvote comments (probably an un-upvote function again, for easier implementation)
- [x] Sort comments by: Most Votes (default), Oldest to Newest (chronological order to follow discussion more easily; if got time)
- [x] Edit comments
- [x] Search for comments
- [x] Pagination

### CODE REVIEW

**Comment by seelengxd** [comment]
could u please help to add Dockerfile :] thankss

**Comment by seelengxd** [comment]
(tried to deploy - i think the problem may be the dockerfile (?))

**Comment by seelengxd** [comment]
update(deployment):

image

somehow throwing typescript errors that i cant replicate locally 💀

**Comment by carriezhengjr** [comment]
> update(deployment):
> 
> image
> somehow throwing typescript errors that i cant replicate locally 💀

I tried to fix lines 194 and 237 in backend/forum-service/src/controllers/forumControllers.ts

Not sure if it will work 🙏

Urghhh why is there still a red cross ❌💀

**Comment by seelengxd** [comment]
thanks, the typescript errors are fixed! :D (then it was another prisma error thing)

**Review by sltsheryl — APPROVED** [review]
Thank you everyone for helping to fix the errors! @carriezhengjr @juslam19 @seelengxd 

current forum
Screenshot 2023-11-10 at 8 14 40 PM

**Pull request merged**
