### PR TITLE
feat: put create form in a card

### PR DESCRIPTION
**Pull request by seelengxd**
image

### CODE REVIEW

**Comment by chloeelim** [comment]
Possible to shift the link to question form above the description box? the spacing there looks slightly off ><

**Comment by chloeelim** [comment]
Added a cancel button here + alert dialog here!


https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g17/assets/79991214/fce6e2e2-6762-4b9e-8000-00f09d2ea65b

**Review by chloeelim — APPROVED** [review]
LGTM I think unless you wanna review my changes on this PR as well hahah thank you! :))

**Comment by seelengxd** [comment]
nice!

**Pull request merged**
