### PR TITLE
[frontend] feat: add code editor

### LINKED ISSUE #42: Code Editor beside Individual Question

### PR DESCRIPTION
**Pull request by chloeelim**
https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g17/assets/79991214/525f9f1b-79f4-4ccc-bcde-981fc834e94c

Adds the code editor to the individual question page.

Current features
* Multi language support (there are 36 languages being currently supported), the list of supported languages can be found in `frontend/src/types/code/languages.ts`
* For the supported languages, syntax highlighting and basic auto-formatting should be supported
* Only certain languages have rich `IntelliSense` (code-completion aid: List Members, Parameter Info, Quick Info, and Complete Word...) and validation now [TypeScript, JavaScript, CSS, JSON, HTML]
* The remaining languages only have basic syntax highlighting (might need to install third-party packages to support them/ write our own)
* Editor theme toggling (light/dark/high contrast light/ high contrast dark)
* Font size toggling
* File download
* File import

Addresses https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g17/issues/42

### CODE REVIEW

**Review by seelengxd — COMMENTED** [review]
looks so cool as usual :D

languages a bit sus - was it intended to have
CSS, Dockerfile, Graphql, JSON, Markdown, Plain Text
as a programming language choice? o_O

**Comment by juslam19** [comment]
Fantastic work! However, agree with See Leng -- Perhaps remove "langauges" not commonly used in coding tests.

**Comment by sltsheryl** [comment]
agreed it looks very good :)

**Comment by chloeelim** [comment]
Thanks! Edited accordingly, feel free to change the list anytime : ) @seelengxd @juslam19 @sltsheryl

**Review by seelengxd — APPROVED** [review]
LGTM! is the plain text programming language the scratchpad :P?

**Comment by chloeelim** [comment]
@seelengxd nopee, included it as a 'backup' option users can choose if their preferred language isn't there- though this might be a bit sketchy indeed 🤔

**Pull request merged**
